version: '3.7'
services:
  logging:
    image: logging:latest
    container_name: logging
    volumes:
      - type: volume
        source: logs
        target: /var/log/tools/
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - type: volume
        source: logs
        target: /var/log/tools

volumes:
  logs:
